[dev]
framework = "#static"
command = "eleventy --quiet --watch"

[build]
command = "eleventy"
publish = "dist/"

[functions]
directory = "netlify/functions/"

[[redirects]]
from = "/stories"
to = "/.netlify/functions/stories"
status = 200
force = true
_generated_by_eleventy_serverless = "stories"

[[redirects]]
from = "/stories/page/:page"
to = "/.netlify/functions/stories"
status = 200
force = true
_generated_by_eleventy_serverless = "stories"
