[dev]
framework = "#static"
command = "eleventy --quiet --watch"

[build]
command = "eleventy"
publish = "dist/"

[functions]
directory = "netlify/functions/"

[[redirects]]
from = "/wp/hook"
to = "/.netlify/functions/hook"
status = 200
force = true
